name: Unit Test
on:
  pull_request:
    branches:
      - dev
jobs:
  vitest:
    environment: test
    timeout-minutes: 20

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/ci-setup
      - name: test
        run: npm run test:unit
        env:
          VITE_PROJECT_ID: ${{ secrets.VITE_PROJECT_ID }}
          VITE_SEED_PHRASE: ${{ secrets.VITE_SEED_PHRASE }}
          VITE_WALLET_PASSWORD: ${{ secrets.VITE_WALLET_PASSWORD }}
          VITE_TEST_CP_URL_1: ${{ secrets.VITE_TEST_CP_URL_1 }}
          VITE_TEST_CP_URL_2: ${{ secrets.VITE_TEST_CP_URL_2 }}
  coverage:
    runs-on: ubuntu-latest
    
    permissions:
      # Required to checkout the code
      contents: read
      # Required to put a comment into the pull-request
      pull-requests: write

    steps:
    - uses: actions/checkout@v4
    - name: 'Install Node'
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
    - name: 'Install Deps'
      run: npm install
    - name: 'Test'
      run: npx vitest --coverage.enabled true
      env:
        VITE_PROJECT_ID: ${{ secrets.VITE_PROJECT_ID }}
        VITE_SEED_PHRASE: ${{ secrets.VITE_SEED_PHRASE }}
        VITE_WALLET_PASSWORD: ${{ secrets.VITE_WALLET_PASSWORD }}
        VITE_TEST_CP_URL_1: ${{ secrets.VITE_TEST_CP_URL_1 }}
        VITE_TEST_CP_URL_2: ${{ secrets.VITE_TEST_CP_URL_2 }}
    - name: 'Report Coverage'
      # Set if: always() to also generate the report if tests are failing
      # Only works if you set `reportOnFailure: true` in your vite config as specified above
      if: always() 
      uses:  davelosert/vitest-coverage-report-action@v2
